#jwt:
#  secretKey: 19OWKGcb49lDR7NUUVcgC/kaIqBm93fQqtisX0naaJ4=
#  expire: 604800000
#  refresh_expire: 86400000
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/resturant_db?createDatabaseIfNotExist=true
#    username: root
#    password: 2025
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

# ===== JWT Settings =====
jwt:
  secretKey: 19OWKGcb49lDR7NUUVcgC/kaIqBm93fQqtisX0naaJ4=
  expire: 604800000        # 7 أيام بالمللي ثانية
  refresh_expire: 86400000 # 1 يوم بالمللي ثانية

# ===== Datasource Settings =====
spring:
  datasource:
    url: jdbc:postgresql://dpg-d67qk7h4tr6s739oc1k0-a.oregon-postgres.render.com:5432/restaurants_db_ghtu?sslmode=require
    username: restaurants_db_ghtu_user
    password: O01MyIMEDtgSjGc4u00pEaEoO4BPrdhb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # سيقوم بإنشاء الجداول تلقائيًا إذا لم تكن موجودة
    show-sql: true         # لعرض استعلامات SQL في الـ console

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
