apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-backend
  template:
    metadata:
      labels:
        app: restaurant-backend
    spec:
      containers:
        - name: restaurant-backend
          image: salah529/restaurant-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/resturant_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2025"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: restaurant
spec:
  type: LoadBalancer
  selector:
    app: restaurant-backend
  ports:
    - port: 8080
      targetPort: 8080
