apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-frontend
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
        - name: restaurant-frontend
          image: salah529/restaurant-frontend
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend-service:8080/api/v1
            - name: NEXT_PUBLIC_ENVIRONMENT
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: restaurant
spec:
  type: LoadBalancer
  selector:
    app: restaurant-frontend
  ports:
    - port: 3000
      targetPort: 3000
